export const GLOBAL_ACTION = Object.freeze({
  SET_GLOBAL_LANG: Symbol('SET_GLOBAL_LANG'),
  SET_GLOBAL_API_TARGET: Symbol('SET_GLOBAL_API_TARGET'),
});
export const MESSAGE_ACTION = Object.freeze({
  SET_MESSAGE_DIALOG: Symbol('SET_MESSAGE_DIALOG'),
  REMOVE_MESSAGE_DIALOG: Symbol('REMOVE_MESSAGE_DIALOG'),
  SET_MESSAGE_CONFIRM: Symbol('SET_MESSAGE_CONFIRM'),
  REMOVE_MESSAGE_CONFIRM: Symbol('REMOVE_MESSAGE_CONFIRM'),
});
export const ORDERBOARD_ACTION = Object.freeze({
  SET_ORDERBOARD_LIST: Symbol('SET_ORDERBOARD_LIST'),
  SET_ORDERBOARD_ITEMS: Symbol('SET_ORDERBOARD_ITEMS'),
});
