export const GLOBAL_ACTION = Object.freeze({
  SET_GLOBAL_LANG: Symbol('SET_GLOBAL_LANG'),
  SET_GLOBAL_SIDEBAR: Symbol('SET_GLOBAL_SIDEBAR'),
});
export const MESSAGE_ACTION = Object.freeze({
  SET_MESSAGE_DIALOG: Symbol('SET_MESSAGE_DIALOG'),
  REMOVE_MESSAGE_DIALOG: Symbol('REMOVE_MESSAGE_DIALOG'),
  SET_MESSAGE_CONFIRM: Symbol('SET_MESSAGE_CONFIRM'),
  REMOVE_MESSAGE_CONFIRM: Symbol('REMOVE_MESSAGE_CONFIRM'),
});
export const TODO_ACTION = Object.freeze({
  SET_TODO_LIST: Symbol('SET_TODO_LIST'),
  SET_TODO_ITEMS: Symbol('SET_TODO_ITEMS'),
});
